### ISSUE TITLE
OAuth2: Google

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#136]
Thunderbird uses OAuth2 scope `https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar` (see https://searchfox.org/comm-central/source/mailnews/base/src/OAuth2Providers.sys.mjs), but Google tells us that this is not necessary for IMAP:

"If your app uses [IMAP protocol or joint IMAP/SMTP protocols](https://developers.google.com/gmail/imap/xoauth2-protocol#:~:text=The%20XOAUTH2%20mechanism%20allows%20clients,shown%20in%20the%20following%20sections.), note that the https://mail.google.com/ scope should only be requested if your application also needs to immediately and permanently delete threads and messages, bypassing Trash; all other actions can be performed with less permissive scopes. If your app does not do this, you will need to migrate to the [Gmail API](https://developers.google.com/gmail/imap/xoauth2-protocol#oauth_20_scopes) and [request less permissive scopes](https://support.google.com/cloud/answer/9110914#requesting-restricted-scopes&zippy)."

So, find our which scope is needed for IMAP, POP3, SMTP, CardDAV, CalDAV and the Google REST API for calendar (not CalDAV), and change the Google scope in OAuth2URLs.ts and in the Google client registration.

**Comment by jermy-c** [comment]
### IMAP, POP3, SMTP

It seems like `https://mail.google.com/` is the only scope available scope for IMAP, POP and SMTP. A combination of `gmail.readonly`, `gmail.compose`, `gmail.labels` and `gmail.modify` wouldn't work because we still can't delete an email. I didn't see anything about POP3 so I'm assuming the scope works for both IMAP and POP3.

Google says there's no way to downscope the `https://mail.google.com/` scope for IMAP and STMP:

> If your application uses the IMAP or SMTP protocol: 
> 
> Full mail (mail.google.com) is the only authorization scope for IMAP and SMTP. Please provide a justification for why your application requires this scope. Please note that the https://mail.google.com/ scope should only be requested if your application also needs to immediately and permanently delete threads and messages, bypassing Trash; all other actions can be performed with less permissive scopes. If your app does not permanently delete threads and/or messages, you will need to migrate to the Gmail API and request less permissive scopes.

link: https://support.google.com/cloud/answer/13807380?hl=en&sjid=2818839467319206190-NA#zippy=%2Cdifferent-gmail-scopes

### CardDav

CardDav scope is `https://www.googleapis.com/auth/carddav`. I created a test project and searched for it and also saw it on Stack Overflow. There's no information about it in the docs.

link: https://stackoverflow.com/questions/44975455/what-scopes-are-neccesary-to-access-gmail-contacts-via-carddav

### CalDav

CalDav and Google REST API for calendar scope is `https://www.googleapis.com/auth/calendar`.

### Changes

I think just removing the `https://www.googleapis.com/auth/contacts` should be enough and be less confusing because the consent screen shows duplicates.
<img width="549" alt="圖片" src="https://github.com/user-attachments/assets/41df75f0-c781-45c4-953f-b8c67db680c1">

And with the `https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar` scope should be good it's seems like other apps use the same scope also. The narrower scopes don't seem to give the authorization to delete or share(in some cases).
<img width="812" alt="圖片" src="https://github.com/user-attachments/assets/179cacc3-d9f1-46b8-b427-7603048d3ee2">
<img width="814" alt="圖片" src="https://github.com/user-attachments/assets/8a8ce2dc-efb0-4c0c-a4cd-2f5b8d0b563f">

**Comment by benbucksch** [comment]
Thanks, Jeremy. Indeed, the [docs I found](https://developers.google.com/gmail/imap/xoauth2-protocol#:~:text=The%20XOAUTH2%20mechanism%20allows%20clients,shown%20in%20the%20following%20sections.) also state:
"The scope for IMAP, POP, and SMTP access is https://mail.google.com/."

I asked Google for clarification which scopes they meant. I wrote to Google:

---------------------
API OAuth Dev Verification wrote:
>
> Hello Google Developer,
>
> Thank you so much for your patience with the verification process.
>
> If your app uses [IMAP protocol or joint IMAP/SMTP protocols](https://developers.google.com/gmail/imap/xoauth2-protocol#:~:text=The%20XOAUTH2%20mechanism%20allows%20clients,shown%20in%20the%20following%20sections.), note that the https://mail.google.com/ scope should only be requested if your application also needs to immediately and permanently delete threads and messages, bypassing Trash; all other actions can be performed with less permissive scopes. If your app does not do this, you will need to migrate to the [Gmail API](https://developers.google.com/gmail/imap/xoauth2-protocol#oauth_20_scopes) and [request less permissive scopes](https://support.google.com/cloud/answer/9110914#requesting-restricted-scopes&zippy).


Dear Google,

indeed, our application is inherently an IMAP and SMTP application. We do not need to "immediately and permanently delete threads and messages, bypassing Trash". Could you please tell us which "scope" we should request, given that you state "all other actions can be performed with less permissive scopes"? Which scopes are those? We would be happy to use those. However, we do need IMAP and SMTP.

This issue here is currently blocking the release of our software. Any help would be appreciated.


> What if I don’t want to complete a CASA Assessment?
>
> You can choose to remove the restricted scope(s) from your application and use the recommended Drive API scope https://www.googleapis.com/auth/drive.file, which doesn’t require a security assessment.

We can remove those scopes for now, if that avoids the CASA assessment process and makes the approval faster.

Thanks,

**Comment by benbucksch** [comment]
> removing the https://www.googleapis.com/auth/contacts

Yes, we can do that. (However, that won't help with the approval.)

**Comment by benbucksch** [comment]
Google responded, suggesting that we use only scopes for sending, completely misunderstanding what IMAP is:

The [Workspace API User Data and Developer Policy](https://developers.google.com/workspace/workspace-api-user-data-developer-policy#request-minimum) mandates that permission requests be limited to the critical information necessary to implement your application's services.

You requested the [Restricted](https://support.google.com/cloud/answer/13464325?hl=en&ref_topic=13460882&sjid=12324348774670791249-NC) Gmail API scope https://mail.google.com/. Based on the information you provided, we believe the Sensitive Gmail API scope https://www.googleapis.com/auth/gmail.send—which allows users to compose and send email messages from the application—may be a better fit for your use case. You should only request the restricted gmail.compose scope if the app also needs to manage drafts within the source Gmail account.

Since gmail.send is not restricted, an additional third-party [security assessment](https://appdefensealliance.dev/casa) will also not be [required](https://support.google.com/cloud/answer/13465431?sjid=12324348774670791249-NC) before your project can be approved or to be [reverified annually](https://support.google.com/cloud/answer/13463816?sjid=12324348774670791249-NC). This will result in a faster and more streamlined verification process for your application.

**Comment by benbucksch** [comment]
> > removing the https://www.googleapis.com/auth/contacts
> 
> Yes, we can do that. (However, that won't help with the approval.)

Done

**Comment by benbucksch** [comment]
Google originally asked for an [ADA CASA](https://appdefensealliance.dev/casa/tier-2/ast-guide?hl=de) validation using a third party audit, which costs a lot of money. I've now paid for that and triggered the validation.

**Comment by benbucksch** [comment]
The auditor told us that we passed the audit and that they will write the Letter of Approval/Validation to Google.

**Comment by benbucksch** [comment]
Many weeks later, the audit finished, and we were approved by Google.
