### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#142]
Please test whether [auto-updates](https://www.electron.build/auto-update) work.

They should be driven by the [latest-mac.yaml](https://github.com/mustang-im/mustang/releases/latest/download/latest-mac.yml) file.

This is a follow-up to #106.

**Comment by benbucksch** [comment]
Also need to add the autoUpdate check to the app code. Unclear whether in the main process in `e2/src/main/index.ts` or whether in the renderer process in `app/logic/startup.ts`.

**Comment by jermy-c** [comment]
I called `autoUpdater.checkForUpdatesAndNotify()` in `e2/src/main/index.ts` and gives me a notification saying an update is available for download. After that, it gives me another notification saying it's ready to install but it doesn't install it on exit or when closing all the windows.

I even called `autoUpdater.quitAndInstall()` when all windows are closed.

<img width="376" alt="圖片" src="https://github.com/user-attachments/assets/159a684d-8624-439c-85b2-07460e900965">

It might be because the app isn't code signed according to the docs.
> macOS application must be [signed](https://www.electron.build/code-signing) in order for auto updating to work.

**Comment by benbucksch** [comment]
Mac signing is #97

**Comment by benbucksch** [comment]
Can you make a PR for triggering the update? Maybe it works on other systems.

**Comment by jermy-c** [comment]
Ok, will do.

**Comment by benbucksch** [comment]
Jeremy wrote in #151 [comment 21](https://github.com/mustang-im/mustang/issues/151#issuecomment-2286766250):
Auto-update is still not working. The update is downloaded but it is not installed when all windows are closed or when the app is quit. I'm not sure if it's supposed to install when the app is quit or when all windows are closed. If the condition to install the update when the all windows are closed it may be because the backend is still running. But the notification message says it will install when the app is quit.

**Comment by benbucksch** [comment]
@jermy-c I've included electron-updater 6.3.3
Could you please check whether the auto-update now works with both Mustang 0.6.0 and Parula 0.6.0?

**Comment by jermy-c** [comment]
Yes, it works for both Mustang 0.6.0 and Parula 0.6.0.

**Comment by benbucksch** [comment]
That's great! Thanks for all your help here!

**Comment by benbucksch** [comment]
The updater worked on Linux with deb. The update info came as system notification. It required that I restart the app, and that I enter the root password, given that it was installed in /opt/ .
