### ISSUE TITLE
OAuth2: Yahoo

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#162]
We finally got the OAuth2 client ID from Yahoo. I've added them to branch `yahoo-oauth2`. Yet, I get "invalid request" error message (in the auth window, inside the webpage, at the very bottom, in grey). I don't know why. Is it because the Client ID has not yet been deployed to Yahoo's production servers? Did we misconfigure something? Does Yahoo not like our request? Are parameters missing? Malformed? Too much (like `login_hint`)?

Could you please find out what's wrong, and fix it?

**Comment by benbucksch** [comment]
We're opening auth URL https://api.login.yahoo.com/oauth2/request_auth?client_id=dj0yJmk9d25qSWNOMzJVeDhlJmQ9WVdrOVV6VTJiMjQzTTFZbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTE3&response_type=code&redirect_uri=https%3A%2F%2Fmustang.im%2Floggedin&response_mode=query&scope=mail-w&state=00031&login_hint=ben%40yahoo.de

Auth window error msg says: "Developers: Please specify a valid request and submit again"

**Comment by jermy-c** [comment]
`error_description: invalid code challenge or method`
It might be, because it requires PKCE. Trying to confirm if that's the fix.

https://github.com/thunderbird/thunderbird-android/issues/7159#issuecomment-1731285127

**Comment by jermy-c** [comment]
PKCE seems to be the problem, I got through the first part of the OAuth flow when `code_challenge` and `code_challenge_method` are added. But after logging in and authorization there's some errors:

1. The redirect URI doesn't match the one registered on YDN because the app's one is `https://www.mustang.im/loggedin` and the one registered is `https://mustang.im/loggedin`
2. When I set the condition to ignore that I get an `json?.error?.replace is not a function` error but that's an OAuth2Error.ts problem
3. If I `console.log()` I get an error:
```json
{
    "localizedMessage": "client request is not acceptable or not supported",
    "errorId": "INVALID_INPUT",
    "message": "client request is not acceptable or not supported"
}
```

The docs don't mention anything about about PKCE though.
