### ISSUE TITLE
ActiveSync: Outlook.com: The user account does not exist in the outlook.com directory

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#212]
### Reproduction
* Set up an @outlook.com account in Mustang
* Choose ActiveSync as protocol

### Actual result
* Error: "Please login"

![image](https://github.com/user-attachments/assets/ed569e02-5697-465b-baed-89f60a0c8b2a)

* Debug output:
```
OAuth2.ts:105 OAuth2ServerError: The user account {EUII Hidden} does not exist in the outlook.com directory. To sign into this application, the account must be added to the directory.
    at _OAuth2.getAccessTokenFromParams (OAuth2.ts:209:13)
    at async _OAuth2.login (OAuth2.ts:103:16)
    at async ActiveSyncAccount.verifyLogin (ActiveSyncAccount.ts:126:9)
    at async checkConfig (checkConfig.ts:8:5)
    at async CheckConfig.svelte:19:3
login @ OAuth2.ts:105
SetupMail.svelte:215 OAuth2LoginNeeded: Please login
    at _OAuth2.login (http://localhost:5454/logic/Auth/OAuth2.ts?t=1726290411389:87:13)
    at async ActiveSyncAccount.verifyLogin (http://localhost:5454/logic/Mail/ActiveSync/ActiveSyncAccount.ts?t=1726290411389:103:9)
    at async checkConfig (http://localhost:5454/logic/Mail/AutoConfig/checkConfig.ts?t=1726290411389:9:5)
    at async http://localhost:5454/frontend/Settings/Setup/Mail/CheckConfig.svelte?t=1726290411389:90:4
```

### Expected result
* Outlook.com OAuth2 login appears in a window
* Can log in
* Account gets set up
* Can fetch emails

### Other results
* It works with Office365 business email accounts like foo@foo.onmicrosoft.com

**Comment by jermy-c** [comment]
> Outlook.com OAuth2 login appears in a window

Because in OAuth2 it is going to use password login if it has the `tokenURLPasswordAuth`

https://github.com/mustang-im/mustang/blob/b27db0a25bf1e08c8917791c9df541c3cd7d0dc5/app/logic/Auth/OAuth2.ts#L101

And in `OAuthURLs` it is set for `outlook.office365.com`
https://github.com/mustang-im/mustang/blob/b27db0a25bf1e08c8917791c9df541c3cd7d0dc5/app/logic/Auth/OAuth2URLs.ts#L18

So basically it does OAuth2 password login regardless of the account type.

But even after successfully getting the token by doing a login with the UI, I'm still getting an `HTTP 451` error

**Comment by jermy-c** [comment]
No, because it only the `/organizations` endpoint supports password login. And the `/organizations` endpoint doesn't support personal accounts.

> The Microsoft identity platform only supports the ROPC grant within Microsoft Entra tenants, not personal accounts. This means that you must use a tenant-specific endpoint (https://login.microsoftonline.com/{TenantId_or_Name}) or the organizations endpoint.

https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth-ropc

**Comment by benbucksch** [comment]
> No, because only the /organizations endpoint supports password login. And the /organizations endpoint doesn't support personal accounts.

OK, I disabled that.

**Comment by benbucksch** [comment]
> even after successfully getting the token by doing a login with the UI, I'm still getting an HTTP 451 error

@jermy-c Could you look into that, please?

**Comment by jermy-c** [comment]
> OK, I disabled that.

Thanks. It's showing a "Please Login" error because of here and other areas where interactive is `false`:

https://github.com/mustang-im/mustang/blob/17894a07c206304ba18dd6b478a6e00c26b48a5c/app/logic/Mail/ActiveSync/ActiveSyncAccount.ts#L206

**Comment by benbucksch** [comment]
> It's showing a "Please Login" error

Even on latest master?

**Comment by jermy-c** [comment]
> Even on latest master?

Yes because if it's false and there's no `tokenURLPasswordAuth` then an error would be thrown.

https://github.com/mustang-im/mustang/blob/b27db0a25bf1e08c8917791c9df541c3cd7d0dc5/app/logic/Auth/OAuth2.ts#L101-L110

**Comment by benbucksch** [comment]
What I see with a business account and ActiveSync is:
* Auto-Login on startup does not work.
  * No error
  * "Disconnected" icon shows on the account in the account list
* Click on the Inbox triggers a login dialog. That is auto-filled and closes by itself, without user input.
* Login works (or at least seems to work)

@jermy-c Is that what you see as well, or do you see something else?

**Comment by jermy-c** [comment]
This is what I see. When I click next it doesn't login but just refreshes and shows the error again.

<img width="596" alt="圖片" src="https://github.com/user-attachments/assets/70b9146c-fb0b-4cc8-b670-ca3e8e5dc9fe">

**Comment by jermy-c** [comment]
Turns out it's using the OAuth2 Auth header i.e. `Bearer {token}` before even getting the token so it's actually `Bearer undefined`. But after I get this error:

<img width="601" alt="圖片" src="https://github.com/user-attachments/assets/684ba419-61e6-481b-b5ea-cf8bdae2953c">

**Comment by jermy-c** [comment]
> Turns out it's using the OAuth2 Auth header i.e. `Bearer {token}` before even getting the token so it's actually `Bearer undefined`. But after I get this error:

This only part of the problem I'm still getting an error even on Post Man.

**Comment by benbucksch** [comment]
```
async verifyLogin() {
  ...
  if (this.oAuth2) {
    await this.oAuth2.login(true);
    options.headers.Authorization = this.oAuth2.authorizationHeader;
  } else {
```

**Comment by jermy-c** [comment]
Findings so far:

1. Personal accounts use `Basic {Auth}` for the OPTIONS request
2. Business accounts use `Bearer {Auth}` for the OPTIONS request
3. After a successful OPTIONS request for personal accounts, the [`ActiveSync version(s) 15.20 not supported`](https://github.com/mustang-im/mustang/issues/212#issuecomment-2362382808) is shown

**Comment by NeilRashbrook** [comment]
`15.20` is a spurious value, the ActiveSync `verifyLogin` error message is using `MSServerActiveSync` which contains an implementation-specific version string instead of `MSASProtocolVersions` which contains the actual ActiveSync versions supported by the server. (We don't actually use `MSServerActiveSync` in mustang; it is used in Owl but only to guess the Exchange version for the error message.)

**Comment by jermy-c** [comment]
The `MSASProtocolVersions` is `2.5,14.0` for personal accounts but the header value in `callEAS` is `"MS-ASProtocolVersion": "14.1"`.

**Comment by NeilRashbrook** [comment]
According to Wikipedia, there are some minor differences between 14.0 and 14.1:
- Support for IRM
- Support for GAL Photos
- Support for downloading individual message parts (possibly? this is terribly documented)
- Support for sending device information as part of provisioning

Regarding provisioning, 14.0 doesn't use the `DeviceInformation` child of the `Provision` request, instead, it is expected to send a separate `Settings` request. I don't know how important this `Settings` request is, but I've written the relevant code in branch `neil/activesync-version-14.0` for it. However, I was only able to test with Office 365 as when I tried to use an @outlook.com account with ActiveSync I got an HTTP 451 which apparently means I'm using the wrong server.

Also, sorry for the mixup with `verifyLogin`; originally I was running into the problem that the UI was trying to log in before the account was saved, and I had the bright idea of creating a function called `verifyLogin` to handle that case, not realising that it already existed; I hadn't noticed because Office 365 password token auth was still enabled at that time so I was able to log in even without the correct code.

**Comment by NeilRashbrook** [comment]
> So, password login doesn't work?

It was never guaranteed to work. In my original EWS-specific implementation, it was tried once, and if it failed (other than the user needing to allow the app) then it was disabled and never tried again. Have you all until now only been ever testing using an account where password login works or something? I know I have.

**Comment by jermy-c** [comment]
`neil/activesync-version-14.0` seems to work ActiveSync for personal accounts if the `Cookie` is set with the `Set-Cookie` value from the `HTTP 451` reponse

**Comment by benbucksch** [comment]
@NeilRashbrook  wrote:

> > So, password login doesn't work?
> It was never guaranteed to work. [I have] only been ever testing using an account where password login works

Under which exact conditions does it work?
