### ISSUE TITLE
OWA: Only 50 emails are downloaded per folder

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#278]
**Reproduction**

1. Login to OWA
2. Click folder properties on a folder
3. Switch between folders

**Actual Result**

1. Each folder only has a maximum of 50 emails
2. Even if you click download it still doesn't download the other emails

**Expected Result**

1. Downloads all emails

**Comment by benbucksch** [comment]
I can confirm that, with neil@ account set up as OWA in a fresh profile, and folders "Deleted Items", "Sent Items" and others.

### Actual result
* After clicking on the folder, I see onljy 50 messages
* In the folder properties (hover over folder name, then click "..."), I see that the folder has over 4000 msgs, 50 local messages
* Clicking [Download all messages] has no effect

### Expected result
* The headers of all messages show up
* Messages are downloaded in the background, in batches of 50.

### Cause
* Apparently, the batching code is stopping and not looping anymore.
* I also tried with v0.6.14, before my changed to the locking code, and the bug is still there.
* Could it be that it deadlocks itself, in the OWA locking/queueing code? Just a guess.

**Comment by benbucksch** [comment]
When I do the same with an EWS account, and I can see in folder properties how the "local messages" are counting up in steps of 50. Not with OWA.
