### ISSUE TITLE
Release Builds: Empty message pane

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#289]
### Reproduction 1

1. Install release build
2. Open app
3. Select a folder
4. Select a message

**Actual Result**

1. The message pane stays empty, even the header pane.
2. Occasionally, it shows a message, but most of the time, it ignore message changes. 
3. There are no error messages

**Expected Result**

1. Display selected message

### Reproduction 2

1. Build app
2. Open app
4. Select a folder

**Actual Result**

1. Once a folder is selected it, cannot be changed, i.e. the UI ignores the selected folder after the first selected folder
2. There are no error messages

**Expected Result**

1. Display selected folder

**Comment by jermy-c** [comment]
The last working version is `0.6.13`

**Comment by benbucksch** [comment]
When I made regression tests on my laptop, the last working version was 0.6.3,
and the first version with the bug was 0.6.6. (The versions in-between had other
bugs that prevented me from seeing this bug.)



Note that the app downloads updates in the background and might automatically
install them, so maybe only the first run of the app is actually the right
version. You see the actual version in Settings | About.



If indeed you and me see different results, then it could be that this is a race
condition.

**Comment by jermy-c** [comment]
The release build works with svelte-collections `v1.1.22`, any version above breaks the release build.

d6d7a2cebe43d2520bb75f718e7acb075ded6184

**Comment by benbucksch** [comment]
Released 0.6.20 with the fix here.
